# Generated by Django 4.2 on 2025-05-09 04:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_price_alter_book_stock_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockevent',
            name='scheduled_for',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 4, 16, 1, 688873, tzinfo=datetime.timezone.utc)),
        ),
    ]
